[package]
name = "minicraft-launcher"
version = "0.1.0"
description = "A Tauri App"
authors = ["KalmeMarq"]
license = ""
repository = ""
default-run = "minicraft-launcher"
edition = "2021"
rust-version = "1.57"

[build-dependencies]
tauri-build = { version = "1.1.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.1.0", features = ["api-all", "updater"] }

[features]
default = [ "custom-protocol" ]

custom-protocol = [ "tauri/custom-protocol" ]
